-- Bootstrap all claudespace custom modules.
-- Runs after plugins/ui.lua so icons and theme are already active.

require('claudespace.repos').setup()
require('claudespace.tabline').setup()
require('claudespace.filetree').setup()
require('claudespace.statusline').setup()
require('claudespace.winbar').setup()
require('claudespace.dirdash').setup()
require('claudespace.workspace').setup()
require('claudespace.home').setup()
require('claudespace.tasks').setup()
require('claudespace.outline').setup()
require('claudespace.funcnav').setup()
require('claudespace.gotofile').setup()
require('claudespace.mdpreview').setup()
require('claudespace.zen').setup()
require('claudespace.mdtoc').setup()
require('claudespace.sidebar').setup()
require('claudespace.notify').setup()
require('claudespace.marks').setup()
require('claudespace.palette').setup()
require('claudespace.git_ui').setup()
require('claudespace.claude.context').setup()
require('claudespace.claude.codegen').setup()
require('claudespace.claude.fix').setup()
require('claudespace.claude.assist').setup()
require('claudespace.claude.workspace').setup()
require('claudespace.test_ui').setup()
require('claudespace.templates').setup()
