-- Workspace context injection for Claude sessions.
-- Generates a context summary and writes it to .claude/WORKSPACE.md,
-- which Claude Code reads automatically on session start.
local M = {}

local fn = vim.fn

local function read_file_head(path, lines)
  if fn.filereadable(path) == 0 then return nil end
  local all = fn.readfile(path)
  if not all or #all == 0 then return nil end
  local take = {}
  for i = 1, math.min(lines, #all) do take[i] = all[i] end
  return table.concat(take, '\n')
end

local function active_cwd()
  return require('claudespace.repos').active_cwd()
end

local function git(cmd, cwd)
  local out = fn.trim(fn.system('git -C ' .. fn.shellescape(cwd) .. ' ' .. cmd .. ' 2>/dev/null'))
  return vim.v.shell_error == 0 and out or ''
end

local function generate(cwd)
  cwd          = cwd or active_cwd()
  local name   = fn.fnamemodify(cwd, ':t')
  local branch = git('branch --show-current', cwd)
  local status = git('status --short', cwd)
  local log    = git('log --oneline -8', cwd)

  local parts = {}
  local function add(s) table.insert(parts, s) end

  add('# Workspace: ' .. name)
  add('**Directory:** `' .. fn.fnamemodify(cwd, ':~') .. '`')
  if branch ~= '' then add('**Branch:** `' .. branch .. '`') end
  add('')

  if status ~= '' then
    add('## Working tree')
    add('```')
    add(status)
    add('```')
    add('')
  end

  if log ~= '' then
    add('## Recent commits')
    add('```')
    add(log)
    add('```')
    add('')
  end

  -- Recent open files
  local oldfiles = vim.v.oldfiles or {}
  local recent = {}
  for _, f in ipairs(oldfiles) do
    if fn.filereadable(f) == 1 and f:sub(1, #cwd) == cwd and #recent < 6 then
      table.insert(recent, fn.fnamemodify(f, ':~:.'))
    end
  end
  if #recent > 0 then
    add('## Recently edited')
    for _, f in ipairs(recent) do add('- `' .. f .. '`') end
    add('')
  end

  -- README excerpt
  local readme = read_file_head(cwd .. '/README.md', 25)
  if readme then
    add('## README (excerpt)')
    add(readme)
    add('')
  end

  -- Workspace map: in a multi-repo workspace, tell Claude the shape of the whole
  -- system (every repo's purpose + intra-workspace dependencies) so a session
  -- scoped to one repo still understands how it fits with the others.
  local ok_repos, repos = pcall(require, 'claudespace.repos')
  if ok_repos and repos.is_multi() then
    local active = repos.at(cwd)
    add('## Workspace map: ' .. (repos.name() or '?')
        .. ' (' .. #repos.list() .. ' repos)')
    if active then add('This session is scoped to `' .. active.path .. '`.') end
    add('')
    add('### Repositories')
    for _, m in ipairs(repos.list()) do
      local purpose = repos.purpose(m)
      add('- `' .. m.path .. '`' .. (purpose and ('  — ' .. purpose) or ''))
    end
    add('')

    local graph = repos.dependency_graph()
    if next(graph) then
      add('### Intra-workspace dependencies')
      for _, m in ipairs(repos.list()) do
        if graph[m.path] then
          add('- `' .. m.path .. '` → ' .. table.concat(graph[m.path], ', '))
        end
      end
      -- Who depends on the active repo (reverse edges) — useful for impact.
      if active then
        local dependents = {}
        for from, tos in pairs(graph) do
          for _, to in ipairs(tos) do
            if to == active.path then dependents[#dependents + 1] = from end
          end
        end
        if #dependents > 0 then
          table.sort(dependents)
          add('')
          add('**Dependents of `' .. active.path .. '`:** '
              .. table.concat(dependents, ', '))
        end
      end
      add('')
    end
  end

  add('---')
  add('*Auto-generated by claudespace.nvim — ' .. os.date('%Y-%m-%d %H:%M') .. '*')

  return table.concat(parts, '\n')
end

---Update `.claude/WORKSPACE.md` in the active repo's root.
function M.update(cwd)
  cwd           = cwd or active_cwd()
  local dir     = cwd .. '/.claude'
  local outfile = dir .. '/WORKSPACE.md'
  fn.mkdir(dir, 'p')
  local content = generate(cwd)
  pcall(fn.writefile, vim.split(content, '\n', { plain = true }), outfile)
end

---Inject workspace context into a specific terminal job (called on session start).
---@param job_id number
---@param cwd?   string
function M.inject_to_job(job_id, cwd)
  if not job_id or job_id <= 0 then return end
  cwd           = cwd or active_cwd()
  local dir     = cwd .. '/.claude'
  local outfile = dir .. '/WORKSPACE.md'
  fn.mkdir(dir, 'p')
  pcall(fn.writefile, vim.split(generate(cwd), '\n', { plain = true }), outfile)
  pcall(fn.chansend, job_id, '@' .. outfile .. '\n')
end

---Send arbitrary text to the active Claude session's terminal job.
---@param text string
---@return boolean
function M.send_to_active(text)
  local sess = require('claudespace.claude.sessions').active()
  if not sess then
    vim.notify('claudespace: no active Claude session', vim.log.levels.WARN)
    return false
  end
  for _, b in ipairs(vim.api.nvim_list_bufs()) do
    if vim.b[b].cs_session_id == sess.id and vim.bo[b].buftype == 'terminal' then
      local job = vim.b[b].terminal_job_id
      if job then pcall(fn.chansend, job, text); return true end
    end
  end
  vim.notify('claudespace: Claude session buffer not found', vim.log.levels.WARN)
  return false
end

---Inject context into the active Claude terminal session.
function M.inject()
  local cwd = active_cwd()
  M.update(cwd)
  local outfile = cwd .. '/.claude/WORKSPACE.md'
  local sent = M.send_to_active('@' .. outfile .. '\n')
  vim.notify(
    sent and 'Context injected into Claude session'
          or 'Context written to .claude/WORKSPACE.md',
    vim.log.levels.INFO
  )
end

---Send the last ~60 lines from the most recent non-Claude terminal to Claude.
function M.send_terminal_output()
  local term_buf = nil
  for _, b in ipairs(vim.api.nvim_list_bufs()) do
    if vim.api.nvim_buf_is_loaded(b)
      and vim.bo[b].buftype == 'terminal'
      and not vim.b[b].cs_session_id then
      term_buf = b
    end
  end
  if not term_buf then
    vim.notify('claudespace: no terminal output found', vim.log.levels.WARN); return
  end
  local total = vim.api.nvim_buf_line_count(term_buf)
  local raw   = vim.api.nvim_buf_get_lines(term_buf, math.max(0, total - 60), total, false)
  local clean = {}
  for _, l in ipairs(raw) do
    clean[#clean + 1] = l:gsub('\27%[[%d;]*[A-Za-z]', ''):gsub('\27%[[%d;]*m', '')
  end
  local output = vim.trim(table.concat(clean, '\n'))
  if output == '' then
    vim.notify('claudespace: terminal output is empty', vim.log.levels.WARN); return
  end
  if M.send_to_active('Here is the terminal output:\n```\n' .. output .. '\n```\n') then
    vim.notify('Terminal output sent to Claude', vim.log.levels.INFO)
  end
end

---Send current file's LSP diagnostics to the active Claude session.
function M.send_diagnostics()
  local bufnr = vim.api.nvim_get_current_buf()
  local fname = fn.fnamemodify(vim.api.nvim_buf_get_name(bufnr), ':~:.')
  local diags = vim.diagnostic.get(bufnr)
  if #diags == 0 then
    vim.notify('claudespace: no diagnostics in current buffer', vim.log.levels.WARN); return
  end
  local sevmap = { 'ERROR', 'WARN', 'INFO', 'HINT' }
  local lines  = { 'Diagnostics for `' .. fname .. '`:' }
  for _, d in ipairs(diags) do
    lines[#lines + 1] = ('  [%s] line %d: %s%s'):format(
      sevmap[d.severity] or '?', d.lnum + 1, d.message,
      d.source and (' (%s)'):format(d.source) or '')
  end
  if M.send_to_active(table.concat(lines, '\n') .. '\n') then
    vim.notify(#diags .. ' diagnostic(s) sent to Claude', vim.log.levels.INFO)
  end
end

-- One entry point for feeding context to Claude — replaces the old cluster of
-- six separate keymaps (@mention, tree file, cross-repo, workspace, terminal,
-- diagnostics).
function M.add_context()
  local items = {
    { 'Current file / selection  (@mention)', function() pcall(vim.cmd, 'ClaudeCodeSend') end },
    { 'File from the tree',                    function() pcall(vim.cmd, 'ClaudeCodeTreeAdd') end },
    { 'Cross-repo files…',                     function() require('claudespace.claude.workspace').add_files() end },
    { 'Workspace context',                     M.inject },
    { 'Terminal output',                       M.send_terminal_output },
    { 'Diagnostics',                           M.send_diagnostics },
  }
  vim.ui.select(items, {
    prompt = 'Add to Claude context',
    format_item = function(x) return x[1] end,
  }, function(x) if x then x[2]() end end)
end

function M.setup()
  local map = vim.keymap.set
  map('n', '<leader>cA', M.add_context, { desc = 'Claude: add to context…', silent = true })

  vim.api.nvim_create_autocmd('User', {
    pattern  = 'ClaudespaceWorkspaceSaved',
    callback = M.update,
  })
  vim.api.nvim_create_autocmd('DirChanged', {
    callback = function() vim.schedule(M.update) end,
  })
end

return M
