-- Workspace context injection for Claude sessions.
-- Generates a context summary and writes it to .claude/WORKSPACE.md,
-- which Claude Code reads automatically on session start.
local M = {}

local fn = vim.fn

local function read_file_head(path, lines)
  if fn.filereadable(path) == 0 then return nil end
  local all = fn.readfile(path)
  if not all or #all == 0 then return nil end
  local take = {}
  for i = 1, math.min(lines, #all) do take[i] = all[i] end
  return table.concat(take, '\n')
end

local function git(cmd)
  local out = fn.trim(fn.system('git -C ' .. fn.shellescape(fn.getcwd()) .. ' ' .. cmd .. ' 2>/dev/null'))
  return vim.v.shell_error == 0 and out or ''
end

local function generate()
  local cwd    = fn.getcwd()
  local name   = fn.fnamemodify(cwd, ':t')
  local branch = git('branch --show-current')
  local status = git('status --short')
  local log    = git('log --oneline -8')

  local parts = {}
  local function add(s) table.insert(parts, s) end

  add('# Workspace: ' .. name)
  add('**Directory:** `' .. fn.fnamemodify(cwd, ':~') .. '`')
  if branch ~= '' then add('**Branch:** `' .. branch .. '`') end
  add('')

  if status ~= '' then
    add('## Working tree')
    add('```')
    add(status)
    add('```')
    add('')
  end

  if log ~= '' then
    add('## Recent commits')
    add('```')
    add(log)
    add('```')
    add('')
  end

  -- Recent open files
  local oldfiles = vim.v.oldfiles or {}
  local recent = {}
  for _, f in ipairs(oldfiles) do
    if fn.filereadable(f) == 1 and f:sub(1, #cwd) == cwd and #recent < 6 then
      table.insert(recent, fn.fnamemodify(f, ':~:.'))
    end
  end
  if #recent > 0 then
    add('## Recently edited')
    for _, f in ipairs(recent) do add('- `' .. f .. '`') end
    add('')
  end

  -- README excerpt
  local readme = read_file_head(cwd .. '/README.md', 25)
  if readme then
    add('## README (excerpt)')
    add(readme)
    add('')
  end

  add('---')
  add('*Auto-generated by claudespace.nvim — ' .. os.date('%Y-%m-%d %H:%M') .. '*')

  return table.concat(parts, '\n')
end

---Update `.claude/WORKSPACE.md` in the current project root.
function M.update()
  local cwd     = fn.getcwd()
  local dir     = cwd .. '/.claude'
  local outfile = dir .. '/WORKSPACE.md'
  fn.mkdir(dir, 'p')
  local content = generate()
  pcall(fn.writefile, vim.split(content, '\n', { plain = true }), outfile)
end

---Inject context into the active Claude terminal session.
---Sends the context file path as a Claude @ reference.
function M.inject()
  M.update()
  local outfile = fn.getcwd() .. '/.claude/WORKSPACE.md'

  -- Try to send to active Claude terminal
  local sent = false
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if vim.bo[buf].buftype == 'terminal' then
      local name = vim.api.nvim_buf_get_name(buf)
      if name:match('claude') then
        local job = vim.b[buf].terminal_job_id
        if job then
          pcall(vim.fn.chansend, job, '@' .. outfile .. '\n')
          sent = true
          -- Make sure the terminal is visible
          for _, win in ipairs(vim.api.nvim_list_wins()) do
            if vim.api.nvim_win_get_buf(win) == buf then
              vim.api.nvim_set_current_win(win)
              break
            end
          end
          break
        end
      end
    end
  end

  if sent then
    vim.notify('Context injected into Claude session', vim.log.levels.INFO)
  else
    vim.notify('Context written to .claude/WORKSPACE.md', vim.log.levels.INFO)
  end
end

function M.setup()
  vim.keymap.set('n', '<leader>ci', M.inject, { desc = 'Claude: inject workspace context' })

  -- Auto-update context on workspace save
  vim.api.nvim_create_autocmd('User', {
    pattern = 'ClaudespaceWorkspaceSaved',
    callback = M.update,
  })

  -- Update on DirChanged (workspace switch changes cwd)
  vim.api.nvim_create_autocmd('DirChanged', {
    callback = function() vim.schedule(M.update) end,
  })
end

return M
